
language: objective-c
osx_image: xcode11.1
xcode_workspace: HooqApp.xcworkspace # path to your xcodeproj folder
xcode_scheme: TravisCIBlog
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone X
before_install:
    - pod install
