
os: osx
language: swift
osx_image: xcode11.1
script: xcodebuild clean build test -workspace HooqApp.xcworkspace -scheme "HooqCI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.1,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
#xcode_workspace: HooqApp.xcworkspace # path to your xcodeproj folder
#xcode_scheme: HooqApp
#xcode_destination: platform=iOS Simulator,OS=13.1,name=iPhone X
before_install:
    - pod install
